package com.kris.mithril;

public enum TokenType {
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    RUNE, FORGE, QUEST, BEAR, SPEAK, SHOULD, LEST, WANDER, WHILST, IN, FELLOWSHIP, MINE,
    LIGHT, SHADOW, NAUGHT, DOOM, WARD, AND, OR, WISE, WIZARD,

    EOF
}